2024-03-17 18:40:12,298: asyncio: INFO: [AITrader] Executing the initialize lifecycle method
2024-03-17 18:40:12,512: alpaca.trading.stream: INFO: connected to: wss://paper-api.alpaca.markets/stream
2024-03-17 18:40:12,936: root: INFO: Current backtesting datetime 2024-01-16 08:30:00-05:00
2024-03-17 18:40:12,936: asyncio: INFO: [AITrader] Executing the before_market_opens lifecycle method
2024-03-17 18:40:12,937: root: INFO: Current backtesting datetime 2024-01-16 09:30:00-05:00
2024-03-17 18:40:12,937: asyncio: INFO: [AITrader] Executing the before_starting_trading lifecycle method
2024-03-17 18:40:12,938: asyncio: INFO: [AITrader] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-17 18:40:12[0m
2024-03-17 18:40:12,945: asyncio: INFO: [AITrader] [31mAn error occurred during the on_trading_iteration lifecycle method: Order quantity must be a positive number[0m
2024-03-17 18:40:12,947: asyncio: INFO: [AITrader] [31mTraceback (most recent call last):
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy_executor.py", line 365, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 72, in on_trading_iteration
    order = self.create_order(
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy.py", line 663, in create_order
    order = Order(
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\entities\order.py", line 249, in __init__
    raise ValueError("Order quantity must be a positive number")
ValueError: Order quantity must be a positive number
[0m
2024-03-17 18:40:12,947: asyncio: INFO: [AITrader] Executing the on_bot_crash event method
2024-03-17 18:40:12,947: asyncio: INFO: [AITrader] [34mSleeping for 86400 seconds[0m
2024-03-17 18:40:12,948: root: INFO: Current backtesting datetime 2024-01-16 16:00:00-05:00
2024-03-17 18:40:12,949: root: INFO: Current backtesting datetime 2024-01-17 09:30:00-05:00
2024-03-17 18:40:12,949: asyncio: INFO: [AITrader] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-17 18:40:12[0m
2024-03-17 18:40:12,951: asyncio: INFO: [AITrader] [31mAn error occurred during the on_trading_iteration lifecycle method: Order quantity must be a positive number[0m
2024-03-17 18:40:12,951: asyncio: INFO: [AITrader] [31mTraceback (most recent call last):
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy_executor.py", line 365, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 72, in on_trading_iteration
    order = self.create_order(
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy.py", line 663, in create_order
    order = Order(
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\entities\order.py", line 249, in __init__
    raise ValueError("Order quantity must be a positive number")
ValueError: Order quantity must be a positive number
[0m
2024-03-17 18:40:12,951: asyncio: INFO: [AITrader] Executing the on_bot_crash event method
2024-03-17 18:40:14,623: asyncio: INFO: [AITrader] [34mSleeping for 86400 seconds[0m
2024-03-17 18:40:14,624: root: INFO: Current backtesting datetime 2024-01-17 16:00:00-05:00
2024-03-17 18:40:14,624: root: INFO: Current backtesting datetime 2024-01-18 09:30:00-05:00
2024-03-17 18:40:14,624: asyncio: INFO: [AITrader] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-17 18:40:14[0m
2024-03-17 18:40:14,627: asyncio: INFO: [AITrader] [31mAn error occurred during the on_trading_iteration lifecycle method: Order quantity must be a positive number[0m
2024-03-17 18:40:14,627: asyncio: INFO: [AITrader] [31mTraceback (most recent call last):
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy_executor.py", line 365, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 72, in on_trading_iteration
    order = self.create_order(
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy.py", line 663, in create_order
    order = Order(
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\entities\order.py", line 249, in __init__
    raise ValueError("Order quantity must be a positive number")
ValueError: Order quantity must be a positive number
[0m
2024-03-17 18:40:14,627: asyncio: INFO: [AITrader] Executing the on_bot_crash event method
2024-03-17 18:40:15,149: asyncio: INFO: [AITrader] [34mSleeping for 86400 seconds[0m
2024-03-17 18:40:15,150: root: INFO: Current backtesting datetime 2024-01-18 16:00:00-05:00
2024-03-17 18:40:15,151: root: INFO: Current backtesting datetime 2024-01-19 09:30:00-05:00
2024-03-17 18:40:15,151: asyncio: INFO: [AITrader] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-17 18:40:15[0m
2024-03-17 18:40:15,154: asyncio: INFO: [AITrader] [31mAn error occurred during the on_trading_iteration lifecycle method: Order quantity must be a positive number[0m
2024-03-17 18:40:15,154: asyncio: INFO: [AITrader] [31mTraceback (most recent call last):
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy_executor.py", line 365, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 72, in on_trading_iteration
    order = self.create_order(
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy.py", line 663, in create_order
    order = Order(
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\entities\order.py", line 249, in __init__
    raise ValueError("Order quantity must be a positive number")
ValueError: Order quantity must be a positive number
[0m
2024-03-17 18:40:15,154: asyncio: INFO: [AITrader] Executing the on_bot_crash event method
2024-03-17 18:40:15,846: asyncio: INFO: [AITrader] [34mSleeping for 86400 seconds[0m
2024-03-17 18:40:15,847: root: INFO: Current backtesting datetime 2024-01-19 16:00:00-05:00
2024-03-17 18:40:15,847: root: INFO: Current backtesting datetime 2024-01-20 09:30:00-05:00
2024-03-17 18:40:15,847: asyncio: INFO: [AITrader] [34mThe market is not currently open, skipping this trading iteration[0m
2024-03-17 18:40:15,849: root: INFO: Current backtesting datetime 2024-01-20 09:29:00-05:00
2024-03-17 18:40:15,850: root: INFO: Current backtesting datetime 2024-01-20 09:29:00-05:00
2024-03-17 18:40:15,850: asyncio: INFO: [AITrader] Executing the after_market_closes lifecycle method
2024-03-17 18:40:15,851: root: INFO: Current backtesting datetime 2024-01-22 08:30:00-05:00
2024-03-17 18:40:15,851: asyncio: INFO: [AITrader] Executing the before_market_opens lifecycle method
2024-03-17 18:40:15,852: root: INFO: Current backtesting datetime 2024-01-22 09:30:00-05:00
2024-03-17 18:40:15,852: asyncio: INFO: [AITrader] Executing the before_starting_trading lifecycle method
2024-03-17 18:40:15,853: asyncio: INFO: [AITrader] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-17 18:40:15[0m
2024-03-17 18:40:15,855: asyncio: INFO: [AITrader] [31mAn error occurred during the on_trading_iteration lifecycle method: Order quantity must be a positive number[0m
2024-03-17 18:40:15,855: asyncio: INFO: [AITrader] [31mTraceback (most recent call last):
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy_executor.py", line 365, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 72, in on_trading_iteration
    order = self.create_order(
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy.py", line 663, in create_order
    order = Order(
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\entities\order.py", line 249, in __init__
    raise ValueError("Order quantity must be a positive number")
ValueError: Order quantity must be a positive number
[0m
2024-03-17 18:40:15,855: asyncio: INFO: [AITrader] Executing the on_bot_crash event method
2024-03-17 18:40:16,353: asyncio: INFO: [AITrader] [34mSleeping for 86400 seconds[0m
2024-03-17 18:40:16,354: root: INFO: Current backtesting datetime 2024-01-22 16:00:00-05:00
2024-03-17 18:40:16,354: root: INFO: Current backtesting datetime 2024-01-23 09:30:00-05:00
2024-03-17 18:40:16,355: asyncio: INFO: [AITrader] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-17 18:40:16[0m
2024-03-17 18:40:16,358: asyncio: INFO: [AITrader] [31mAn error occurred during the on_trading_iteration lifecycle method: Order quantity must be a positive number[0m
2024-03-17 18:40:16,358: asyncio: INFO: [AITrader] [31mTraceback (most recent call last):
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy_executor.py", line 365, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 72, in on_trading_iteration
    order = self.create_order(
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy.py", line 663, in create_order
    order = Order(
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\entities\order.py", line 249, in __init__
    raise ValueError("Order quantity must be a positive number")
ValueError: Order quantity must be a positive number
[0m
2024-03-17 18:40:16,358: asyncio: INFO: [AITrader] Executing the on_bot_crash event method
2024-03-17 18:40:16,868: asyncio: INFO: [AITrader] [34mSleeping for 86400 seconds[0m
2024-03-17 18:40:16,869: root: INFO: Current backtesting datetime 2024-01-23 16:00:00-05:00
2024-03-17 18:40:16,869: root: INFO: Current backtesting datetime 2024-01-24 09:30:00-05:00
2024-03-17 18:40:16,870: asyncio: INFO: [AITrader] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-17 18:40:16[0m
2024-03-17 18:40:16,872: asyncio: INFO: [AITrader] [31mAn error occurred during the on_trading_iteration lifecycle method: Order quantity must be a positive number[0m
2024-03-17 18:40:16,872: asyncio: INFO: [AITrader] [31mTraceback (most recent call last):
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy_executor.py", line 365, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 72, in on_trading_iteration
    order = self.create_order(
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy.py", line 663, in create_order
    order = Order(
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\entities\order.py", line 249, in __init__
    raise ValueError("Order quantity must be a positive number")
ValueError: Order quantity must be a positive number
[0m
2024-03-17 18:40:16,872: asyncio: INFO: [AITrader] Executing the on_bot_crash event method
2024-03-17 18:40:17,366: asyncio: INFO: [AITrader] [34mSleeping for 86400 seconds[0m
2024-03-17 18:40:17,367: root: INFO: Current backtesting datetime 2024-01-24 16:00:00-05:00
2024-03-17 18:40:17,368: root: INFO: Current backtesting datetime 2024-01-25 09:30:00-05:00
2024-03-17 18:40:17,368: asyncio: INFO: [AITrader] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-17 18:40:17[0m
2024-03-17 18:40:17,370: asyncio: INFO: [AITrader] [31mAn error occurred during the on_trading_iteration lifecycle method: Order quantity must be a positive number[0m
2024-03-17 18:40:17,370: asyncio: INFO: [AITrader] [31mTraceback (most recent call last):
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy_executor.py", line 365, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 72, in on_trading_iteration
    order = self.create_order(
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy.py", line 663, in create_order
    order = Order(
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\entities\order.py", line 249, in __init__
    raise ValueError("Order quantity must be a positive number")
ValueError: Order quantity must be a positive number
[0m
2024-03-17 18:40:17,370: asyncio: INFO: [AITrader] Executing the on_bot_crash event method
2024-03-17 18:40:17,891: asyncio: INFO: [AITrader] [34mSleeping for 86400 seconds[0m
2024-03-17 18:40:17,893: root: INFO: Current backtesting datetime 2024-01-25 16:00:00-05:00
2024-03-17 18:40:17,893: root: INFO: Current backtesting datetime 2024-01-26 09:30:00-05:00
2024-03-17 18:40:17,893: asyncio: INFO: [AITrader] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-17 18:40:17[0m
2024-03-17 18:40:17,896: asyncio: INFO: [AITrader] [31mAn error occurred during the on_trading_iteration lifecycle method: Order quantity must be a positive number[0m
2024-03-17 18:40:17,896: asyncio: INFO: [AITrader] [31mTraceback (most recent call last):
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy_executor.py", line 365, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 72, in on_trading_iteration
    order = self.create_order(
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy.py", line 663, in create_order
    order = Order(
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\entities\order.py", line 249, in __init__
    raise ValueError("Order quantity must be a positive number")
ValueError: Order quantity must be a positive number
[0m
2024-03-17 18:40:17,896: asyncio: INFO: [AITrader] Executing the on_bot_crash event method
2024-03-17 18:40:18,419: asyncio: INFO: [AITrader] [34mSleeping for 86400 seconds[0m
2024-03-17 18:40:18,420: root: INFO: Current backtesting datetime 2024-01-26 16:00:00-05:00
2024-03-17 18:40:18,420: root: INFO: Current backtesting datetime 2024-01-27 09:30:00-05:00
2024-03-17 18:40:18,421: asyncio: INFO: [AITrader] [34mThe market is not currently open, skipping this trading iteration[0m
2024-03-17 18:40:18,423: root: INFO: Current backtesting datetime 2024-01-27 09:29:00-05:00
2024-03-17 18:40:18,424: root: INFO: Current backtesting datetime 2024-01-27 09:29:00-05:00
2024-03-17 18:40:18,424: asyncio: INFO: [AITrader] Executing the after_market_closes lifecycle method
2024-03-17 18:40:18,425: root: INFO: Current backtesting datetime 2024-01-29 08:30:00-05:00
2024-03-17 18:40:18,425: asyncio: INFO: [AITrader] Executing the before_market_opens lifecycle method
2024-03-17 18:40:18,426: root: INFO: Current backtesting datetime 2024-01-29 09:30:00-05:00
2024-03-17 18:40:18,426: asyncio: INFO: [AITrader] Executing the before_starting_trading lifecycle method
2024-03-17 18:40:18,427: asyncio: INFO: [AITrader] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-17 18:40:18[0m
2024-03-17 18:40:18,429: asyncio: INFO: [AITrader] [31mAn error occurred during the on_trading_iteration lifecycle method: Order quantity must be a positive number[0m
2024-03-17 18:40:18,429: asyncio: INFO: [AITrader] [31mTraceback (most recent call last):
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy_executor.py", line 365, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 72, in on_trading_iteration
    order = self.create_order(
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy.py", line 663, in create_order
    order = Order(
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\entities\order.py", line 249, in __init__
    raise ValueError("Order quantity must be a positive number")
ValueError: Order quantity must be a positive number
[0m
2024-03-17 18:40:18,429: asyncio: INFO: [AITrader] Executing the on_bot_crash event method
2024-03-17 18:40:18,920: asyncio: INFO: [AITrader] [34mSleeping for 86400 seconds[0m
2024-03-17 18:40:18,921: root: INFO: Current backtesting datetime 2024-01-29 16:00:00-05:00
2024-03-17 18:40:18,922: root: INFO: Current backtesting datetime 2024-01-30 09:30:00-05:00
2024-03-17 18:40:18,922: asyncio: INFO: [AITrader] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-17 18:40:18[0m
2024-03-17 18:40:18,924: asyncio: INFO: [AITrader] [31mAn error occurred during the on_trading_iteration lifecycle method: Order quantity must be a positive number[0m
2024-03-17 18:40:18,924: asyncio: INFO: [AITrader] [31mTraceback (most recent call last):
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy_executor.py", line 365, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 72, in on_trading_iteration
    order = self.create_order(
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy.py", line 663, in create_order
    order = Order(
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\entities\order.py", line 249, in __init__
    raise ValueError("Order quantity must be a positive number")
ValueError: Order quantity must be a positive number
[0m
2024-03-17 18:40:18,924: asyncio: INFO: [AITrader] Executing the on_bot_crash event method
2024-03-17 18:40:19,417: asyncio: INFO: [AITrader] [34mSleeping for 86400 seconds[0m
2024-03-17 18:40:19,418: root: INFO: Current backtesting datetime 2024-01-30 16:00:00-05:00
2024-03-17 18:40:19,419: root: INFO: Current backtesting datetime 2024-01-31 09:30:00-05:00
2024-03-17 18:40:19,420: root: INFO: Current backtesting datetime 2024-01-31 15:59:00-05:00
2024-03-17 18:40:19,420: asyncio: INFO: [AITrader] Executing the before_market_closes lifecycle method
2024-03-17 18:40:19,421: root: INFO: Current backtesting datetime 2024-01-31 16:00:00-05:00
2024-03-17 18:40:19,421: asyncio: INFO: [AITrader] Executing the after_market_closes lifecycle method
2024-03-17 18:40:19,421: asyncio: INFO: [AITrader] Executing the on_strategy_end lifecycle method
2024-03-17 18:40:19,937: root: INFO: Backtesting finished
2024-03-17 18:40:20,166: root: INFO: There were no trades in this backtest.
2024-03-17 18:40:20,570: root: ERROR: Not enough data to create a tearsheet, at least 2 days of data are required. Skipping
2024-03-17 18:40:20,571: backtest_stats: INFO: Backtest took 0:00:08.274193 for a speed of 0.000
